name: zincsight
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - pymol-open-source=3.0.0
  - scipy
  - biopython=1.78
  - matplotlib
  - psycopg2-binary
  - scikit-learn
  - python-dotenv
  - joblib
  - aria2p
  - pydash
  - pip:
      - appdirs==1.4.4
      - aria2p==0.12.0
      - loguru==0.7.2
      - psycopg2-binary==2.9.9
      - pgserver==0.1.4